apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: packetbeat-dynamic
  labels:
    app: packetbeat-dynamic
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
